spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resources_class?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: chengehang99
# MinIO配置
minio:
  # 服务地址
  endpoint: http://223.2.54.119:9099
  # 文件地址
  fileHost: http://223.2.54.119:9099
  # 存储桶名称
  bucket: madfile
  # 用户名
  access-key: minioadmin
  # 密码
  secret-key: minioadmin